import Head from "next/head";
import styles from "../../styles/Home.module.css";
import AppBar from "../../components/appbar";
import { ILoginPage } from "./index.d.ts";
import { useEffect } from "react";

function LoginPageContent(props: ILoginPage) {
  useEffect(() => {
    console.log(props);
  }, []);

  const { handleSubmitLoginForm, handleSetInputValue } = props;
  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>

      <AppBar />

      <div
        style={{ display: "flex", flexDirection: "column", maxWidth: "300px" }}
      >
        <h3>Temporary form</h3>

        <div style={{ display: "flex", flexDirection: "column" }}>
          <label htmlFor="email">email</label>
          <input
            onChange={(event) =>
              handleSetInputValue(event.target.name, event.target.value)
            }
            type="text"
            name="email"
          />
        </div>

        <div
          style={{
            display: "flex",
            flexDirection: "column",
            marginBottom: "10px",
          }}
        >
          <label htmlFor="password">password</label>
          <input
            onChange={(event) =>
              handleSetInputValue(event.target.name, event.target.value)
            }
            type="text"
            name="password"
          />
        </div>

        <button
          onClick={handleSubmitLoginForm}
          style={{ padding: "5px", width: "150px" }}
        >
          submit
        </button>
      </div>
    </div>
  );
}

export default LoginPageContent;
