import Head from "next/head";
import styles from "../../styles/Home.module.css";
import AppBar from "../../components/appbar";

function LoginPageContent() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>

      <AppBar />

      <div
        style={{ display: "flex", flexDirection: "column", maxWidth: "300px" }}
      >
        <h3>Temporary form</h3>

        <div style={{ display: "flex", flexDirection: "column" }}>
          <label htmlFor="email">email</label>
          <input type="text" name="email" />
        </div>

        <div
          style={{
            display: "flex",
            flexDirection: "column",
            marginBottom: "10px",
          }}
        >
          <label htmlFor="password">password</label>
          <input type="text" name="password" />
        </div>

        <button style={{ padding: "5px", width: "150px" }}>submit</button>
      </div>
    </div>
  );
}

export default LoginPageContent;
